"use client";

import { useEffect, useRef, useState } from "react";
import Icon from "./Icon";

const focusableSelector = "button:not([disabled]), input:not([disabled]), [href], [tabindex]:not([tabindex='-1'])";
const buttonBase = "inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border px-5 font-bold transition-colors duration-200 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[var(--orange-soft)] disabled:cursor-not-allowed disabled:opacity-50";
const primaryButton = `${buttonBase} border-[var(--orange)] bg-[var(--orange)] text-white hover:bg-[var(--orange-dark)]`;
const inputClasses = "min-h-12 w-full rounded-xl border border-[var(--line)] bg-white px-3.5 py-3 text-[var(--ink)] outline-none transition-[border-color,box-shadow] duration-200 focus:border-[var(--orange)] focus:ring-4 focus:ring-[var(--orange-soft)]";
const labelClasses = "grid gap-2 text-sm font-bold text-[var(--ink)]";
const isValidCard = (number) => { const digits = number.replace(/\D/g, ""); if (digits.length < 13 || digits.length > 19) return false; let sum = 0; let double = false; for (let index = digits.length - 1; index >= 0; index -= 1) { let digit = Number(digits[index]); if (double) { digit *= 2; if (digit > 9) digit -= 9; } sum += digit; double = !double; } return sum % 10 === 0; };
const isFutureExpiry = (value) => { const match = /^(0[1-9]|1[0-2])\/(\d{2})$/.exec(value); if (!match) return false; const expiry = new Date(2000 + Number(match[2]), Number(match[1]), 1); return expiry > new Date(); };

export default function PaymentModal({ open, onClose, amount, title, note, onSuccess }) {
  const [method, setMethod] = useState("upi"); const [processing, setProcessing] = useState(false); const [complete, setComplete] = useState(false); const [upi, setUpi] = useState("demo@rentkaro"); const [cardNumber, setCardNumber] = useState("4242 4242 4242 4242"); const [expiry, setExpiry] = useState("12/29"); const [cvv, setCvv] = useState("123"); const [error, setError] = useState("");
  const dialogRef = useRef(null); const previousFocus = useRef(null); const processingRef = useRef(processing); const closeRef = useRef(onClose); processingRef.current = processing; closeRef.current = onClose;
  useEffect(() => { if (!open) { setProcessing(false); setComplete(false); setError(""); return; } previousFocus.current = document.activeElement; const previousOverflow = document.body.style.overflow; document.body.style.overflow = "hidden"; window.requestAnimationFrame(() => dialogRef.current?.querySelector(focusableSelector)?.focus()); const handleKeyDown = (event) => { if (event.key === "Escape" && !processingRef.current) { closeRef.current(); return; } if (event.key !== "Tab") return; const controls = [...(dialogRef.current?.querySelectorAll(focusableSelector) || [])]; if (!controls.length) return; const first = controls[0]; const last = controls[controls.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; document.addEventListener("keydown", handleKeyDown); return () => { document.removeEventListener("keydown", handleKeyDown); document.body.style.overflow = previousOverflow; previousFocus.current?.focus?.(); }; }, [open]);
  if (!open) return null;
  const chooseMethod = (nextMethod) => { setMethod(nextMethod); setError(""); };
  const formatCard = (value) => value.replace(/\D/g, "").slice(0, 19).replace(/(.{4})/g, "$1 ").trim();
  const formatExpiry = (value) => { const digits = value.replace(/\D/g, "").slice(0, 4); return digits.length > 2 ? `${digits.slice(0, 2)}/${digits.slice(2)}` : digits; };
  const pay = () => { let nextError = ""; if (method === "upi" && !/^[\w.-]+@[\w.-]+$/.test(upi.trim())) nextError = "Enter a valid UPI ID, such as name@bank."; if (method === "card" && !isValidCard(cardNumber)) nextError = "Enter a valid card number."; else if (method === "card" && !isFutureExpiry(expiry)) nextError = "Enter a future expiry date in MM/YY format."; else if (method === "card" && !/^\d{3,4}$/.test(cvv)) nextError = "Enter a 3 or 4 digit CVV."; if (nextError) { setError(nextError); return; } setError(""); setProcessing(true); window.setTimeout(() => { setProcessing(false); setComplete(true); window.setTimeout(() => { onSuccess(); onClose(); }, 650); }, 900); };
  return <div className="fixed inset-0 z-[var(--z-backdrop)] flex items-end justify-center bg-[rgb(10_10_10/68%)] sm:items-center sm:p-5" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && !processing && onClose()}><section className="relative z-[var(--z-modal)] max-h-[calc(100dvh-1rem)] w-full overflow-y-auto rounded-t-2xl bg-white px-5 pb-[calc(1.25rem+env(safe-area-inset-bottom))] pt-6 shadow-[var(--shadow-lg)] motion-safe:animate-modal sm:max-h-[calc(100dvh-40px)] sm:w-[min(100%,520px)] sm:rounded-2xl sm:p-8" ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="payment-title" aria-describedby="payment-note">
    <div className="mx-auto mb-5 h-1 w-12 rounded-full bg-[var(--line)] sm:hidden" aria-hidden="true"/><button className="absolute right-4 top-4 grid size-11 place-items-center rounded-xl border border-[var(--line)] bg-white text-[var(--ink)] transition-colors hover:border-[var(--ink)] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[var(--orange-soft)] disabled:opacity-50 sm:right-5 sm:top-5" onClick={onClose} disabled={processing} aria-label="Close payment"><Icon name="close"/></button>
    {complete ? <div className="grid min-h-[300px] place-items-center text-center" role="status"><div><span className="mx-auto grid size-16 place-items-center rounded-xl bg-[var(--ink)] text-white"><Icon name="check" size={30}/></span><h2 className="mt-5 text-2xl font-bold">Payment confirmed</h2><p className="mt-2 text-[var(--muted)]">Your marketplace workspace is updating now.</p></div></div> : <><header className="pr-12"><span className="inline-flex items-center gap-2 text-sm font-bold text-[var(--orange-dark)]"><Icon name="shield" size={17}/> Secure simulation</span><h2 className="mt-3 text-balance text-2xl font-bold" id="payment-title">{title}</h2><p className="mt-2 max-w-[46ch] leading-6 text-[var(--muted)]" id="payment-note">{note}</p></header><div className="my-5 flex items-center justify-between border-y border-[var(--line)] py-4"><span className="font-semibold">Total payable</span><strong className="text-2xl tabular-nums">₹{Number(amount).toLocaleString("en-IN")}</strong></div>
      <div className="mb-5 grid grid-cols-2 gap-2" role="radiogroup" aria-label="Payment method">{[["upi","UPI","Instant confirmation"],["card","Card","Visa · Mastercard"]].map(([key,label,caption]) => <button type="button" className={`min-h-16 rounded-xl border p-3 text-left transition-colors focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[var(--orange-soft)] ${method === key ? "border-[var(--orange)] bg-[var(--orange-soft)] text-[var(--ink)]" : "border-[var(--line)] bg-white text-[var(--ink)] hover:border-[var(--ink)]"}`} key={key} onClick={() => chooseMethod(key)} role="radio" aria-checked={method === key}><strong className="block">{label}</strong><small className="text-[var(--muted)]">{caption}</small></button>)}</div>
      {method === "upi" ? <label className={labelClasses} htmlFor="upi-id">UPI ID<input className={inputClasses} id="upi-id" value={upi} onChange={(event) => setUpi(event.target.value)} inputMode="email" autoComplete="off" aria-invalid={Boolean(error)} aria-describedby={error ? "payment-error" : undefined}/></label> : <div className="grid gap-3"><label className={labelClasses} htmlFor="card-number">Card number<input className={inputClasses} id="card-number" value={cardNumber} onChange={(event) => setCardNumber(formatCard(event.target.value))} inputMode="numeric" autoComplete="cc-number" aria-invalid={Boolean(error)} aria-describedby={error ? "payment-error" : undefined}/></label><div className="grid grid-cols-2 gap-3"><label className={labelClasses} htmlFor="card-expiry">Expiry MM/YY<input className={inputClasses} id="card-expiry" value={expiry} onChange={(event) => setExpiry(formatExpiry(event.target.value))} inputMode="numeric" autoComplete="cc-exp" placeholder="MM/YY" maxLength={5}/></label><label className={labelClasses} htmlFor="card-cvv">CVV<input className={inputClasses} id="card-cvv" value={cvv} onChange={(event) => setCvv(event.target.value.replace(/\D/g, "").slice(0, 4))} inputMode="numeric" autoComplete="cc-csc" placeholder="3–4 digits" maxLength={4}/></label></div></div>}
      {error && <p className="mt-3 text-sm font-bold text-[var(--red)]" id="payment-error" role="alert">{error}</p>}<button className={`${primaryButton} mt-5 w-full`} onClick={pay} disabled={processing}>{processing ? <><span className="size-[18px] animate-spin rounded-full border-2 border-[rgb(255_255_255/45%)] border-t-white"/>Processing…</> : <>Pay ₹{Number(amount).toLocaleString("en-IN")} <Icon name="arrow"/></>}</button><p className="mt-3 flex items-center justify-center gap-2 text-center text-xs text-[var(--muted)]"><Icon name="lock" size={14}/> Simulation only—no real money is charged.</p></>}
  </section></div>;
}
