"use client";

import { useState } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import Icon from "./Icon";
import PaymentModal from "./PaymentModal";
import { useMarketplace } from "@/lib/marketplace-context";
import { useAuth } from "@/lib/auth-context";

const buttonBase = "inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border px-5 font-bold transition-colors duration-200 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[var(--orange-soft)] disabled:cursor-not-allowed disabled:opacity-50";
const primaryButton = `${buttonBase} border-[var(--orange)] bg-[var(--orange)] text-white hover:bg-[var(--orange-dark)]`;
const secondaryButton = `${buttonBase} border-[var(--line)] bg-white text-[var(--ink)] hover:border-[var(--ink)]`;
const inputClasses = "min-h-12 w-full rounded-xl border border-[var(--line)] bg-white px-3.5 py-3 text-[var(--ink)] outline-none transition-[border-color,box-shadow] duration-200 focus:border-[var(--orange)] focus:ring-4 focus:ring-[var(--orange-soft)]";
const localDateTime = (hoursAhead) => { const date = new Date(Date.now() + hoursAhead * 60 * 60 * 1000); date.setMinutes(Math.ceil(date.getMinutes() / 15) * 15, 0, 0); const offset = date.getTimezoneOffset() * 60000; return new Date(date.getTime() - offset).toISOString().slice(0, 16); };

export default function PropertyDetails() {
  const { id } = useParams();
  const router = useRouter();
  const { user } = useAuth();
  const { state, broker, unlockProperty, bookVisit } = useMarketplace();
  const [paymentType, setPaymentType] = useState(null);
  // Paid actions require a signed-in user. Browsing stays free/public.
  const requireLogin = () => {
    router.push(`/login?next=/properties/${id}`);
  };
  const guard = (action) => () => (user ? action() : requireLogin());
  const [visitDate, setVisitDate] = useState(() => localDateTime(24));
  const property = state.properties.find((item) => item.id === id);
  const unlocked = state.unlocks.some((item) => item.propertyId === id);
  const lead = state.leads.find((item) => item.propertyId === id);
  if (!property) return <section className="grid min-h-[70dvh] place-content-center justify-items-center gap-4 px-5 text-center"><strong className="text-6xl text-[var(--orange)]">404</strong><h1 className="text-3xl font-bold text-[var(--ink)]">This property has moved.</h1><p className="text-[var(--muted)]">It may have been rented or removed from verification.</p><Link className={primaryButton} href="/">Browse available homes</Link></section>;
  const visitMin = localDateTime(1);
  const nextVisitFee = state.totalVisits === 0 ? 0 : 50;
  const canUnlock = property.approved && property.status === "Available";
  const canBook = unlocked && ["Unlocked", "Visited"].includes(lead?.status);
  const token = Math.round(property.rent * 0.15);
  const formattedVisit = visitDate ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(visitDate)) : "";
  const doRequestVisit = () => { if (!canBook || !visitDate || visitDate < visitMin) return; if (nextVisitFee === 0) bookVisit(id, formattedVisit); else setPaymentType("visit"); };
  const requestVisit = guard(doRequestVisit);
  const startUnlock = guard(() => setPaymentType("unlock"));
  const actionLabel = !unlocked ? "Unlock for ₹100" : canBook ? `${nextVisitFee ? `Pay ₹${nextVisitFee} & book` : "Book free visit"}` : "View status";
  const actionHandler = !unlocked ? startUnlock : canBook ? requestVisit : undefined;
  const images = property.images.filter(Boolean).slice(0, 3);
  const hasMultipleImages = images.length > 1;
  return <><main className="mx-auto max-w-[1180px] px-4 pb-36 pt-4 text-[var(--ink)] [&_h2]:leading-tight [&_h2]:tracking-[-0.02em] sm:px-6 sm:pt-7 lg:pb-20">
    <Link className="mb-5 inline-flex min-h-11 items-center gap-2 font-bold text-[var(--ink)] hover:text-[var(--orange-dark)] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[var(--orange-soft)]" href="/"><span aria-hidden="true">←</span> Back to homes</Link>
    <header className="grid gap-5 border-b border-[var(--line)] pb-6 lg:grid-cols-[minmax(0,1fr)_360px] lg:items-end"><div><div className="mb-3 flex flex-wrap items-center gap-2"><span className="inline-flex min-h-8 items-center rounded-lg border border-[var(--line)] bg-white px-3 text-sm font-bold">{property.status}</span><span className="text-sm font-semibold text-[var(--muted)]">Owner verified</span></div><h1 className="max-w-[760px] text-balance text-[clamp(2rem,5vw,4rem)] font-extrabold leading-[1.02] tracking-[-0.035em]">{property.title}</h1><p className="mt-3 flex items-center gap-2 font-semibold text-[var(--muted)]"><Icon name="map" size={18}/>{property.locality}, Pune</p><div className="mt-5 flex flex-wrap items-end gap-x-5 gap-y-2"><strong className="text-3xl tabular-nums">₹{property.rent.toLocaleString("en-IN")}<span className="text-base font-semibold text-[var(--muted)]"> / month</span></strong><span className="text-base font-bold">{property.bhk}</span></div></div>
      <section className={`rounded-2xl border border-[var(--ink)] bg-[var(--ink)] p-5 text-white ${!unlocked ? "hidden lg:block" : ""}`} aria-label="Primary property action"><p className="mb-1 text-sm font-bold text-[oklch(0.82_0.08_55)]">{!unlocked ? "Verified contact" : canBook ? `Next visit · ${nextVisitFee === 0 ? "Free" : "₹50"}` : `Lead status · ${lead?.status || "Assigned"}`}</p><p className="mb-4 text-sm leading-6 text-[oklch(0.82_0_0)]">{!unlocked ? "Pay ₹100 once to reveal the consultant phone number." : canBook ? "Choose a future time below. The first marketplace visit is free; every later visit is ₹50." : "Your current visit is already in progress. Track it in your workspace."}</p>{!unlocked ? <button className={`${primaryButton} w-full`} disabled={!canUnlock} onClick={actionHandler}>Unlock for ₹100 <Icon name="arrow"/></button> : canBook ? <><label className="grid gap-2 text-sm font-bold" htmlFor="visit-date-top">Visit date and time<input className={inputClasses} id="visit-date-top" type="datetime-local" min={visitMin} value={visitDate} onChange={(event) => setVisitDate(event.target.value)}/></label><button className={`${primaryButton} mt-3 w-full`} disabled={!visitDate || visitDate < visitMin} onClick={requestVisit}>{nextVisitFee === 0 ? "Book free visit" : "Continue to ₹50 payment"}<Icon name="calendar"/></button></> : <Link className={`${secondaryButton} w-full`} href="/dashboard?role=client">Open client workspace <Icon name="arrow"/></Link>}</section></header>
    <section className={`mt-5 overflow-hidden rounded-2xl bg-[var(--soft)] ${hasMultipleImages ? "grid h-[300px] grid-cols-2 grid-rows-[2fr_1fr] gap-1.5 sm:h-[520px] sm:grid-cols-[2fr_1fr] sm:grid-rows-2" : "h-[300px] sm:h-[520px]"}`} aria-label="Property photos"><img className={hasMultipleImages ? "col-span-2 h-full w-full object-cover sm:col-span-1 sm:row-span-2" : "h-full w-full object-cover"} src={images[0]} alt={`${property.title} main view`}/>{hasMultipleImages && images.slice(1).map((image, index) => <img className="h-full w-full object-cover" src={image} alt={`${property.title} view ${index + 2}`} key={image}/>)}</section>
    <div className="mt-7 grid gap-8 lg:mt-8 lg:grid-cols-[minmax(0,1fr)_360px] lg:gap-14"><div><section className="grid grid-cols-2 overflow-hidden rounded-2xl border border-[var(--line)] sm:grid-cols-4" aria-label="Core property specifications">{[[property.bhk,"Configuration"],[`${property.area.toLocaleString("en-IN")} sq ft`,"Carpet area"],[property.furnishing,"Furnishing"],[`₹${property.deposit.toLocaleString("en-IN")}`,"Deposit"]].map(([value,label], index) => <div className={`min-w-0 px-3 py-4 ${index < 2 ? "border-b border-[var(--line)]" : ""} ${index % 2 === 0 ? "border-r border-[var(--line)]" : ""} sm:border-b-0 sm:border-r sm:last:border-r-0`} key={label}><strong className="block break-words text-base leading-6 sm:text-lg">{value}</strong><span className="mt-1 block text-sm text-[var(--muted)]">{label}</span></div>)}</section><section className="border-b border-[var(--line)] py-8"><h2 className="text-2xl font-bold">About this home</h2><p className="mt-3 max-w-[70ch] leading-7 text-[var(--ink-2)]">{property.description}</p><p className="mt-3 text-[var(--ink-2)]">Available: <strong>{property.available}</strong>. The exact address is shared after contact unlock.</p></section><section className="border-b border-[var(--line)] py-8"><h2 className="text-2xl font-bold">Amenities</h2><ul className="mt-4 flex list-none flex-wrap gap-2 p-0">{property.amenities.map((amenity) => <li className="inline-flex min-h-10 items-center gap-2 border border-[var(--line)] bg-white px-3 font-semibold" key={amenity}><Icon className="text-[var(--orange-dark)]" name="check" size={17}/>{amenity}</li>)}</ul></section><section className="mt-8 border border-[var(--orange)] bg-[var(--orange-soft)] p-5"><div className="flex gap-3"><Icon className="shrink-0 text-[var(--orange-dark)]" name="info"/><div><h2 className="text-lg font-bold">15% token policy · ₹{token.toLocaleString("en-IN")}</h2><p className="mt-2 leading-6 text-[var(--ink-2)]">On cancellation, <strong>75% is refundable</strong> and <strong>25% is retained as the platform charge</strong>. Full terms are shown before token payment.</p></div></div></section></div>
      <aside className={`h-fit rounded-2xl border border-[var(--line)] bg-white p-5 lg:sticky lg:top-24 ${!unlocked ? "hidden lg:block" : ""}`} aria-label="Consultant contact">{unlocked ? <><span className="inline-flex min-h-8 items-center bg-[var(--orange-soft)] px-3 text-sm font-bold text-[var(--orange-dark)]"><Icon name="lock" size={15}/> Contact unlocked</span><h2 className="mt-4 text-2xl font-bold">{broker.name}</h2><p className="mt-1 text-sm text-[var(--muted)]">Verified partner · {broker.zone} · {broker.rating}/5</p><a className="mt-5 flex min-h-16 items-center gap-3 border border-[var(--ink)] p-3 font-bold text-[var(--ink)] hover:border-[var(--orange)] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[var(--orange-soft)]" href={`tel:${broker.phone.replaceAll(" ", "")}`}><Icon className="text-[var(--orange-dark)]" name="phone"/><span><small className="block font-semibold text-[var(--muted)]">Consultant phone</small>{broker.phone}</span></a><Link className={`${secondaryButton} mt-3 w-full`} href="/dashboard?role=client">Open workspace <Icon name="arrow"/></Link></> : <><Icon className="text-[var(--orange-dark)]" name="lock"/><h2 className="mt-3 text-2xl font-bold">Consultant phone is private</h2><p className="mt-2 leading-6 text-[var(--muted)]">A ₹100 unlock reveals the verified number. Visit pricing is separate and based on your marketplace visit history.</p><button className={`${primaryButton} mt-5 w-full`} disabled={!canUnlock} onClick={startUnlock}>Unlock for ₹100</button></>}</aside></div>
  </main>
  <div className="fixed inset-x-0 bottom-0 z-[var(--z-sticky)] border-t border-[var(--line)] bg-white px-4 pt-3 pb-[calc(0.75rem+env(safe-area-inset-bottom))] shadow-[0_-10px_30px_rgb(0_0_0/10%)] lg:hidden" aria-label="Mobile property action"><div className="mx-auto flex max-w-lg items-center gap-3 max-[390px]:flex-col max-[390px]:items-stretch"><div className="min-w-0 flex-1 max-[390px]:hidden"><strong className="block truncate text-sm">{!unlocked ? "Consultant contact" : canBook ? `Next visit: ${nextVisitFee === 0 ? "Free" : "₹50"}` : lead?.status || "Visit status"}</strong><span className="block truncate text-xs text-[var(--muted)]">{!unlocked ? "One-time ₹100 unlock" : unlocked ? broker.phone : ""}</span></div>{actionHandler ? <button className={`${primaryButton} shrink-0 px-4 max-[390px]:w-full`} disabled={!canUnlock && !unlocked} onClick={actionHandler}>{actionLabel}</button> : <Link className={`${primaryButton} shrink-0 px-4 max-[390px]:w-full`} href="/dashboard?role=client">{actionLabel}</Link>}</div></div>
  <PaymentModal open={Boolean(paymentType)} onClose={() => setPaymentType(null)} amount={paymentType === "visit" ? 50 : 100} title={paymentType === "visit" ? "Confirm your visit" : "Unlock verified broker"} note={paymentType === "visit" ? `Book ${formattedVisit} at ${property.title}.` : `Reveal ${broker.name}’s phone number for this property.`} onSuccess={() => paymentType === "visit" ? bookVisit(id, formattedVisit) : unlockProperty(id)}/></>;
}
