"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import Icon from "./Icon";
import PaymentModal from "./PaymentModal";
import PropertyPhotoManager from "./PropertyPhotoManager";
import { useMarketplace } from "@/lib/marketplace-context";
import { useAuth } from "@/lib/auth-context";
import { subscribeProperty, toMarketplaceProperty } from "@/lib/properties";

const buttonBase = "inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border px-5 font-bold transition-all duration-200 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[var(--orange-soft)] disabled:cursor-not-allowed disabled:opacity-50 active:scale-[.98]";
const primaryButton = `${buttonBase} border-[var(--orange)] bg-[var(--orange)] text-white hover:bg-[var(--orange-dark)]`;
const secondaryButton = `${buttonBase} border-[var(--line)] bg-white text-[var(--ink)] hover:border-[var(--ink)]`;
const inputClasses = "min-h-12 w-full rounded-xl border border-[var(--line)] bg-white px-3.5 py-3 text-[var(--ink)] outline-none focus:border-[var(--orange)] focus:ring-4 focus:ring-[var(--orange-soft)]";
const localDateTime = (hoursAhead) => { const date = new Date(Date.now() + hoursAhead * 3600000); date.setMinutes(Math.ceil(date.getMinutes() / 15) * 15, 0, 0); const offset = date.getTimezoneOffset() * 60000; return new Date(date.getTime() - offset).toISOString().slice(0, 16); };

export default function PropertyDetails() {
  const { id } = useParams(); const router = useRouter(); const { user } = useAuth();
  const { state, broker, unlockProperty, bookVisit } = useMarketplace();
  const [liveProperty, setLiveProperty] = useState(null); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState("");
  const [paymentType, setPaymentType] = useState(null); const [visitDate, setVisitDate] = useState(() => localDateTime(24)); const [galleryOpen, setGalleryOpen] = useState(false); const [saved, setSaved] = useState(false); const [shareStatus, setShareStatus] = useState("");
  useEffect(() => { setLoading(true); setLoadError(""); let unsubscribe; try { unsubscribe = subscribeProperty(id, (record) => { setLiveProperty(record); setLoading(false); }, () => { setLoadError("Live property details could not be loaded."); setLoading(false); }); } catch (error) { setLoadError(error?.message || "Property details could not be loaded."); setLoading(false); } return () => unsubscribe?.(); }, [id]);
  const localProperty = state.properties.find((item) => item.id === id); const property = liveProperty ? toMarketplaceProperty(liveProperty) : localProperty;
  const unlocked = state.unlocks.some((item) => item.propertyId === id); const lead = state.leads.find((item) => item.propertyId === id); const canManagePhotos = user?.admin === 1 || user?.role === "consultant";
  const requireLogin = () => router.push(`/login?next=/properties/${id}`); const guard = (action) => () => user ? action() : requireLogin();
  if (loading && !property) return <main className="site-container min-h-[70dvh] animate-pulse py-12" aria-label="Loading property"><div className="h-10 w-2/3 rounded bg-[var(--soft)]"/><div className="mt-6 h-[420px] rounded-2xl bg-[var(--soft)]"/></main>;
  if (!property) return <section className="grid min-h-[70dvh] place-content-center justify-items-center gap-4 px-5 text-center"><strong className="text-6xl text-[var(--orange)]">404</strong><h1 className="text-3xl font-bold">This property has moved.</h1><p className="text-[var(--muted)]">{loadError || "It may have been rented or removed from verification."}</p><Link className={primaryButton} href="/">Browse available homes</Link></section>;
  const visitMin = localDateTime(1); const nextVisitFee = state.totalVisits === 0 ? 0 : 50; const canUnlock = property.approved && property.status === "Available"; const canBook = unlocked && ["Unlocked", "Visited"].includes(lead?.status); const token = Math.round(property.rent * 0.15);
  const formattedVisit = visitDate ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(visitDate)) : ""; const doRequestVisit = () => { if (!canBook || !visitDate || visitDate < visitMin) return; if (nextVisitFee === 0) bookVisit(id, formattedVisit); else setPaymentType("visit"); };
  const requestVisit = guard(doRequestVisit); const startUnlock = guard(() => setPaymentType("unlock")); const images = (property.images || []).filter(Boolean).slice(0, 8); const mosaic = images.slice(0, 5); const amenities = property.amenities || [];
  const share = async () => { try { if (navigator.share) await navigator.share({ title: property.title, text: `${property.title} in ${property.locality}, Pune`, url: window.location.href }); else await navigator.clipboard.writeText(window.location.href); setShareStatus(navigator.share ? "Shared" : "Link copied"); window.setTimeout(() => setShareStatus(""), 2500); } catch (error) { if (error?.name !== "AbortError") setShareStatus("Could not share"); } };
  const actionLabel = !unlocked ? "Unlock for ₹100" : canBook ? (nextVisitFee ? `Pay ₹${nextVisitFee} & book` : "Book free visit") : "View status"; const actionHandler = !unlocked ? startUnlock : canBook ? requestVisit : undefined;
  return <><main className="site-container pb-36 pt-7 text-[var(--ink)] lg:pb-20"><Link className="inline-flex min-h-11 items-center gap-2 font-bold hover:text-[var(--orange-dark)]" href="/properties"><span aria-hidden="true">←</span> All homes</Link>
    {loadError && <p className="mt-3 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-800" role="alert">{loadError} Showing the last available copy.</p>}
    <header className="mt-4 flex items-start justify-between gap-5 max-[760px]:flex-col"><div><h1 className="max-w-[850px] text-balance text-[clamp(2rem,4.5vw,3.6rem)] font-extrabold leading-[1.04] tracking-[-.04em]">{property.title}</h1><p className="mt-3 flex items-center gap-2 font-semibold text-[var(--muted)]"><Icon name="map" size={18}/>{property.location || `${property.locality}, Pune`}</p></div><div className="flex flex-wrap items-center justify-end gap-2 max-[760px]:justify-start">{canManagePhotos && <PropertyPhotoManager propertyId={id} currentCount={images.length} onUpdated={(nextImages) => setLiveProperty((current) => current ? { ...current, images: nextImages } : current)}/>}<button type="button" onClick={share} className={secondaryButton}><Icon name="share" size={17}/>{shareStatus || "Share"}</button><button type="button" aria-pressed={saved} onClick={() => setSaved((value) => !value)} className={secondaryButton}><Icon name="heart" size={17}/>{saved ? "Saved" : "Save"}</button></div></header>
    <section className={`relative mt-6 grid overflow-hidden rounded-2xl bg-[var(--soft)] ${mosaic.length === 1 ? "h-[320px] sm:h-[520px]" : mosaic.length === 2 ? "h-[340px] grid-cols-2 gap-1.5 sm:h-[520px]" : "h-[390px] grid-cols-2 grid-rows-[2fr_1fr] gap-1.5 sm:h-[520px] sm:grid-cols-4 sm:grid-rows-2"}`} aria-label="Property photos">{mosaic.map((image, index) => <img key={`${image}-${index}`} src={image} alt={`${property.title} view ${index + 1}`} className={`${mosaic.length > 2 && index === 0 ? "col-span-2 h-full w-full object-cover sm:row-span-2" : "h-full w-full object-cover"} ${mosaic.length > 3 && index > 2 ? "hidden sm:block" : ""}`}/>)}{images.length > 1 && <button type="button" onClick={() => setGalleryOpen(true)} className="absolute bottom-4 right-4 inline-flex min-h-11 items-center gap-2 rounded-xl border border-[#222] bg-white px-4 text-sm font-extrabold shadow-sm hover:bg-[#f7f7f7]"><Icon name="grid" size={17}/> Show all {images.length} photos</button>}</section>
    <div className="mt-8 grid gap-10 lg:grid-cols-[minmax(0,1fr)_370px] lg:gap-16"><div><section className="border-b border-[var(--line)] pb-7"><h2 className="text-2xl font-extrabold">{property.bhk} home hosted by a verified owner</h2><p className="mt-2 text-[var(--muted)]">{property.area > 0 ? `${property.area.toLocaleString("en-IN")} sq ft · ` : ""}{property.furnishing} · Available {property.available}</p></section><section className="border-b border-[var(--line)] py-8"><h2 className="text-2xl font-extrabold">About this home</h2><p className="mt-4 max-w-[70ch] leading-7 text-[var(--ink-2)]">{property.description}</p></section><section className="border-b border-[var(--line)] py-8"><h2 className="text-2xl font-extrabold">What this place offers</h2><ul className="mt-5 grid list-none gap-4 p-0 sm:grid-cols-2">{amenities.map((amenity) => <li className="flex items-center gap-3 font-semibold" key={amenity}><Icon className="text-[var(--orange-dark)]" name="check" size={18}/>{amenity}</li>)}</ul></section><section className="mt-8 border-l-4 border-[var(--orange)] bg-[var(--orange-soft)] p-5"><h2 className="text-lg font-extrabold">15% token policy · ₹{token.toLocaleString("en-IN")}</h2><p className="mt-2 leading-6 text-[var(--ink-2)]">On cancellation, <strong>75% is refundable</strong> and <strong>25% is retained as the platform charge</strong>. Full terms are shown before payment.</p></section></div>
      <aside className="h-fit rounded-2xl border border-[var(--line)] bg-white p-6 shadow-[0_18px_55px_rgb(0_0_0/10%)] lg:sticky lg:top-24" aria-label="Property action"><strong className="text-3xl tabular-nums">₹{property.rent.toLocaleString("en-IN")}</strong><span className="font-semibold text-[var(--muted)]"> / month</span><p className="mt-2 text-sm text-[var(--muted)]">Deposit ₹{property.deposit.toLocaleString("en-IN")} · {property.status}</p>{unlocked ? <><div className="my-5 border-y border-[var(--line)] py-5"><span className="text-sm font-bold text-[var(--orange-dark)]">Contact unlocked</span><h2 className="mt-2 text-xl font-extrabold">{broker.name}</h2><a className="mt-3 flex items-center gap-3 font-bold hover:text-[var(--orange-dark)]" href={`tel:${broker.phone.replaceAll(" ", "")}`}><Icon name="phone"/>{broker.phone}</a></div>{canBook ? <><label className="grid gap-2 text-sm font-bold" htmlFor="visit-date">Visit date and time<input className={inputClasses} id="visit-date" type="datetime-local" min={visitMin} value={visitDate} onChange={(event) => setVisitDate(event.target.value)}/></label><button className={`${primaryButton} mt-3 w-full`} disabled={!visitDate || visitDate < visitMin} onClick={requestVisit}>{nextVisitFee === 0 ? "Book free visit" : "Continue to ₹50 payment"}</button></> : <Link className={`${secondaryButton} mt-5 w-full`} href="/dashboard?role=client">Open workspace <Icon name="arrow"/></Link>}</> : <><div className="my-5 border-y border-[var(--line)] py-5"><h2 className="text-xl font-extrabold">Consultant phone is private</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">A one-time ₹100 unlock reveals the verified consultant and enables assisted visits.</p></div><button className={`${primaryButton} w-full`} disabled={!canUnlock} onClick={startUnlock}><Icon name="lock" size={17}/> Unlock for ₹100</button></>}</aside></div>
  </main>{galleryOpen && <div className="fixed inset-0 z-[var(--z-modal)] overflow-y-auto bg-white p-4 sm:p-8" role="dialog" aria-modal="true" aria-label="All property photos"><div className="mx-auto max-w-[1180px]"><div className="sticky top-0 z-10 mb-5 flex items-center justify-between bg-white/95 py-3 backdrop-blur"><h2 className="text-2xl font-extrabold">{property.title} · {images.length} photos</h2><button type="button" onClick={() => setGalleryOpen(false)} className="grid size-12 place-items-center rounded-full border border-[var(--line)] bg-white" aria-label="Close gallery"><Icon name="close"/></button></div><div className="grid gap-3 sm:grid-cols-2">{images.map((image, index) => <img className="w-full rounded-xl object-cover" src={image} alt={`${property.title} photo ${index + 1}`} key={`${image}-gallery`}/>)}</div></div></div>}
  <div className="fixed inset-x-0 bottom-0 z-[var(--z-sticky)] border-t border-[var(--line)] bg-white px-4 py-3 shadow-[0_-10px_30px_rgb(0_0_0/10%)] lg:hidden"><div className="mx-auto flex max-w-lg items-center gap-3"><div className="min-w-0 flex-1"><strong className="block truncate">₹{property.rent.toLocaleString("en-IN")} / month</strong><span className="block truncate text-xs text-[var(--muted)]">{!unlocked ? "One-time ₹100 contact unlock" : broker.phone}</span></div>{actionHandler ? <button className={`${primaryButton} shrink-0 px-4`} disabled={!canUnlock && !unlocked} onClick={actionHandler}>{actionLabel}</button> : <Link className={`${primaryButton} shrink-0 px-4`} href="/dashboard?role=client">{actionLabel}</Link>}</div></div>
  <PaymentModal open={Boolean(paymentType)} onClose={() => setPaymentType(null)} amount={paymentType === "visit" ? 50 : 100} title={paymentType === "visit" ? "Confirm your visit" : "Unlock verified consultant"} note={paymentType === "visit" ? `Book ${formattedVisit} at ${property.title}.` : `Reveal ${broker.name}’s phone number for this property.`} onSuccess={() => paymentType === "visit" ? bookVisit(id, formattedVisit) : unlockProperty(id)}/></>;
}
