export const PLANS_CONFIG = {
  payPerListing: [
    {
      id: "free_7_day",
      name: "Free Listing (7 Days)",
      price: 0,
      period: "7 days",
      badge: "Free Trial",
      features: [
        "1 Pune rental property",
        "7 Days live on search",
        "WhatsApp & callback enquiry enabled",
        "Standard search placement",
      ],
      cta: "List for Free",
    },
    {
      id: "ad_extension_30",
      name: "30-Day Ad Extension",
      price: 149,
      period: "30 days",
      badge: "Popular Renewal",
      features: [
        "Keep your property live for 30 more days",
        "Direct tenant enquiries",
        "Zero brokerage tag for owners",
        "Instant renewal anytime",
      ],
      cta: "Extend Listing",
    },
    {
      id: "verified_badge",
      name: "Verified Badge & Top Rank",
      price: 299,
      period: "30 days",
      badge: "Best Value",
      features: [
        "Verified Owner/Broker badge",
        "Rank on Top of Pune search results",
        "3x more tenant views & clicks",
        "Verified badge credibility boost",
      ],
      cta: "Get Verified Badge",
    },
  ],
  monthlyPlans: [
    {
      id: "starter_owner",
      name: "Starter Owner",
      price: 499,
      period: "month",
      leads: 15,
      featuredBadges: 2,
      badge: "Individual Owners",
      description: "Ideal for individual flat owners looking for genuine tenants quickly with zero brokerage.",
      features: [
        "15 Direct Tenant Leads & Unlocks",
        "2 Featured Verified Badges (Top Rank)",
        "Up to 3 Active Property Listings",
        "30-day listing validity per property",
        "Zero Brokerage Certificate & Highlight",
        "WhatsApp Lead Alerts",
      ],
      cta: "Choose Starter Plan",
    },
    {
      id: "pro_landlord",
      name: "Pro Landlord & Commercial",
      price: 999,
      period: "month",
      leads: 40,
      featuredBadges: 5,
      badge: "Most Popular",
      description: "For regular landlords and commercial property owners with multiple flats or commercial spaces.",
      features: [
        "40 Direct Tenant Leads & Unlocks",
        "5 Featured Verified Badges (Top Rank)",
        "Up to 10 Active Property Listings",
        "60-day listing validity per property",
        "Commercial & Residential inventory support",
        "Priority Search Placement",
        "Direct Landlord Concierge Support",
      ],
      cta: "Choose Pro Plan",
    },
    {
      id: "enterprise_developer",
      name: "Commercial & Enterprise",
      price: 1999,
      period: "month",
      leads: 100,
      featuredBadges: 20,
      badge: "Highest Reach",
      description: "For property developers, commercial building owners, and large portfolio landlords.",
      features: [
        "Unlimited Tenant Leads & Inquiries",
        "Verified Badges on ALL listings (Rank 1 Priority)",
        "Unlimited Property Listings",
        "90-day listing validity",
        "Commercial & Retail spaces spotlight",
        "Dedicated Account & Relationship Manager",
        "Custom Lease Agreement Templates",
      ],
      cta: "Choose Enterprise Plan",
    },
  ]
};
